### ISSUE TITLE
Doesn't work in Sketch 48.1

### ISSUE THREAD

**Issue by rubiroid** [juliussohn/sketch-textbox-fit-content#2]
Seems like plugin doesn't work in 48.1

**Comment by Nikyleast** [comment]
It doesn't work on 48.2 too :(

**Comment by dbrienswann** [comment]
Would love an update to this plugin. Used all the time before Sketch broke the plugin. :(

**Comment by alexeiboronnikov** [comment]
Same here. Need this gem badly.

**Comment by Mar0k** [comment]
Please!  I would need it for Version 49

**Comment by juliussohn** [comment]
The issue has been fixed with [release 1.2 ](https://github.com/juliussohn/sketch-textbox-fit-content/releases/download/v1.2.0/sketch-textbox-fit-content.sketchplugin.zip) and the plugin works with the latest Sketch version (49).
