### ISSUE TITLE
Auto-fit conflicts with the Paddy plugin

### ISSUE THREAD

**Issue by heathflohre** [juliussohn/sketch-textbox-fit-content#4]
When used in conjunction with Paddy (https://github.com/DWilliames/paddy-sketch-plugin), the auto-fit functionality throws a "No layers selected" error and doesn't fit the textbox.

**Comment by juliussohn** [comment]
I see the "No layers selected" message, but the resizing still works. can you give me more details on how you use paddy in this case?
