### ISSUE TITLE
Not rounding to whole numbers

### ISSUE THREAD

**Issue by rlenzen13** [juliussohn/sketch-textbox-fit-content#7]
I appreciate the attention to detail, but I preferred when the box would round to a whole number so that my measurements were exact across the board for design. Would love the ability to change preferences or something somehow.

**Comment by juliussohn** [comment]
Hey @rlenzen13, I appreciate the feedback. 
Sketch has implemented auto-sizing textboxes natively a while ago, so I am not working on this plugin anymore.
